### ISSUE TITLE
Error in cpool

### ISSUE THREAD

**Issue by SohamTamba** [zzzxxxttt/pytorch_simple_cornernet#5]
Cpool works fine when I use it on my laptop but when I use it on my remote HPC, I get the following error

```
Traceback (most recent call last):
  File "final_train.py", line 9, in <module>
    from src.models.downstream.bbox import BboxDecoder
  File "/home/sgt287/DL_Project/src/models/downstream/bbox.py", line 6, in <module>
    from .cpool import TopPool, BottomPool, LeftPool, RightPool
  File "/home/sgt287/DL_Project/src/models/downstream/cpool/__init__.py", line 6, in <module>
    import top_pool, bottom_pool, left_pool, right_pool
ImportError: /home/sgt287/.local/lib/python3.6/site-packages/cpools-0.0.0-py3.6-linux-x86_64.egg/top_pool.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
```

Are there requirements other than:
```
python>=3.5
pytorch==0.4.1 or 1.1.0(DistributedDataParallel training only available using 1.1.0)
tensorboardX(optional)
```
Maybe a version of GCC?

**Comment by zzzxxxttt** [comment]
Did you compile cpool on your remote PC? This error usually because of environment mismatch between compiling and running, by the way, I use gcc-4.9 for compiling.

**Comment by SohamTamba** [comment]
I compiled it again on my remote HPC.

**Comment by SohamTamba** [comment]
I was able to solve the issue by using absolute import instead of relative import.

Not sure why it worked on my PC.

Thanks for your help.
